### ISSUE TITLE
Should be a gap between logo and app name

### ISSUE THREAD

**Issue by hsn-ali** [arvindpndit/stack-doubts#20]
Hi, Hope you're doing well

you can assign me I can work on it.

![image](https://github.com/arvindpndit/stack-doubts/assets/75776012/de24baf7-efa4-4f8f-876f-9353a796d184)

**Comment by arvindpndit** [comment]
Hey @hsn-ali 
Thanks for the feedback but this is the way i designed the logo with the picture and text (intentionally overlapped the text over the picture)

![stack doubts](https://github.com/arvindpndit/stack-doubts/assets/121677260/2a7fb403-a75d-4a82-9f81-9fb97c367987)

**Comment by hsn-ali** [comment]
ok, Thanks I'm closing this issue if you have any small issues you can assign me!
